// <auto-generated />
using BlogProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogProject.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200220000927_FirstSeed")]
    partial class FirstSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogProject.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tom Shaw",
                            Category = "Computers",
                            Content = "Machine learning for humans",
                            PublishDate = "19FEB20",
                            Tags = "Machine Learning",
                            Title = "First Blog"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Samuel Burns",
                            Category = "Travel",
                            Content = "The one stop shop for all your traveling needs",
                            PublishDate = "01JAN19",
                            Tags = "Cleveland",
                            Title = "Travel for Dummies"
                        },
                        new
                        {
                            Id = 3,
                            Author = "John Doe",
                            Category = "Food",
                            Content = "Tasty Snacks with a low price point",
                            PublishDate = "16MAY17",
                            Tags = "Toronto",
                            Title = "Cooking on a Budget"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
